version: '3'

services:
  db:
    image: mdillon/postgis
    restart: unless-stopped
    volumes:
      - argentinahackea_pgdata:/var/lib/postgresql/data

  app:
    build: 
      context: ./src
    environment: 
      DJANGO_SETTINGS_MODULE: "mvp.settings.prod"
      VIRTUAL_PORT: 8000
      VIRTUAL_HOST: "back.52.91.66.153.xip.io,api.entretodos.com.ar"
      LETSENCRYPT_HOST: "api.entretodos.com.ar"
    ports:
      - "8000:8000"
    depends_on: 
      - db
    volumes:
      - ./src:/app
    tty: true
    restart: unless-stopped
    command: gunicorn -b 0.0.0.0:8000 mvp.wsgi --reload

volumes:
  argentinahackea_pgdata:

networks:
  default:
    external:
      name: nginx-proxy
