version: '3'

services:
  db:
    image: mdillon/postgis
    volumes:
      - argentinahackea_pgdata:/var/lib/postgresql/data

  app:
    build: 
      context: ./src
    environment: 
      DJANGO_SETTINGS_MODULE: "mvp.settings.prod"
      VIRTUAL_PORT: "8000"
      VIRTUAL_HOST: "back.34.201.137.122.xip.io"
      #LETSENCRYPT_HOST: "back.34.201.137.122.xip.io"
    ports:
      - "8000:8000"
    depends_on: 
      - db
    volumes:
      - ./src:/app
    tty: true

volumes:
  argentinahackea_pgdata:

networks:
  default:
    external:
      name: nginx-proxy